version: '2'
services: 
  voice:
        build: ./voice
        privileged: true
        restart: always
        labels:
                io.balena.features.dbus: '1'
                io.balena.features.kernel-modules: '1'
        volumes: 
                - 'shared-data:/var/data'
                - 'shared-media:/var/media'
  camera:
        build: ./camera
        privileged: true
        restart: always
        volumes: 
                - 'shared-data:/var/data'
                - 'shared-media:/var/media'
        depends_on:
                - voice
              
        ports:
                - "80"
        labels:
                io.balena.features.kernel-modules: '1'
volumes:
        shared-data: 
        shared-media: